services:
  postgres:
    image: postgres:16.4-bookworm
    ports:
      - '5432:5432'
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      PGDATA: /var/lib/postgresql/data/pgdata
    env_file: .env.compose
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: unless-stopped

  analyzer-cron:
    image: analyzer:latest
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    depends_on:
      - postgres
    restart: unless-stopped
    command:
      - "/app/cron_entrypoint.sh"
      - "--schedule"
      - "0 5 * * *"
      - "/usr/local/bin/python /app/bin/analyzer_cron.py"

volumes:
  pgdata:
